export enum ValidationType {
    VALID_STRING_MIN_LENGTH = 'VALID_STRING_MIN_LENGTH',
    VALID_STRING_MAX_LENGTH = 'VALID_STRING_MAX_LENGTH',
    VALID_NUMBER_MIN = 'VALID_NUMBER_MIN',
    VALID_NUMBER_MAX = 'VALID_NUMBER_MAX',
    VALID_REGEX = 'VALID_REGEX',
}
