import { InputType, VarType } from '../../src/gql/generated/globalTypes';
import { DataContainer } from '../../src/types/DataMapsTypes';

const mockDataContainers = {
    noDataCase: [] as DataContainer[],
    defaultCase: [
        {
            id: '5f3169bsd94190ff3189e',
            persisting_id: '5f3169bsd90ff3189e',
            ConditionFormTester: '5f3169bsdf05e94190ff3189e',
            allow_custom: false,
            name: 'Multiple Condition',
            platform_data_maps: [
                {
                    id: '5f31490dv3',
                    key: 'select',
                    var_type: VarType.ARRAY_STRING,
                    input_type: InputType.MULTIPLE_SELECT,
                    is_optional: false,
                    default_value: null,
                    option_values: ['dsfsdfsdf', 'sdsdf', 'ddd'],
                    description: '...',
                    __typename: 'PlatformDataMap',
                    child_platform_data_maps: [],
                    validation_rules: [],
                },
            ],
            __typename: 'PlatformDataContainer',
            description: '...',
        },
        {
            id: '5f3169be405e94190ff3189e',
            persisting_id: '5f3169be405e94190ff3189e',
            ConditionFormTester: '5f3169be405e94190ff3189e',
            allow_custom: false,
            name: 'Cookies',
            platform_data_maps: [],
            __typename: 'PlatformDataContainer',
            description: '...',
        },
        {
            id: '5f3169be405e94190ff3189d',
            persisting_id: '5f3169be405e94190ff3189d',
            allow_custom: true,
            name: 'Consent test',
            platform_data_maps: [
                {
                    id: '5f3169be405e94190ff318a0',
                    key: 'vendor',
                    var_type: VarType.ARRAY_INT,
                    input_type: InputType.CONSENT_VENDORS,
                    default_value: null,
                    option_values: null,
                    __typename: 'PlatformDataMap',
                    description: '...',
                    is_optional: true,
                    child_platform_data_maps: [],
                },
            ],
            __typename: 'PlatformDataContainer',
            description: '...',
        },
        {
            id: '5f3169be405e94190ff318ae',
            persisting_id: '5f3169be405e94190ff318ae',
            allow_custom: true,
            name: 'Data Layer With also Custom',
            platform_data_maps: [
                {
                    id: '5f3169be405e94190ff318a0',
                    key: 'app_id',
                    var_type: VarType.STRING,
                    input_type: InputType.TEXT,
                    default_value: null,
                    option_values: null,
                    __typename: 'PlatformDataMap',
                    description: '...',
                    is_optional: true,
                    child_platform_data_maps: [],
                },
            ],
            __typename: 'PlatformDataContainer',
            description: '...',
        },
        {
            id: '5f31490d66dba60c29f65dc9',
            persisting_id: '5f31490d66dba60c29f65dc9',
            allow_custom: false,
            name: 'Scale8 Data Layer',
            platform_data_maps: [
                {
                    id: '5f31490cxyxba60c29f65db5',
                    key: 'rawObjRoot',
                    var_type: VarType.OBJECT,
                    input_type: InputType.OBJECT_INPUT,
                    default_value: null,
                    option_values: null,
                    __typename: 'PlatformDataMap',
                    description: '...',
                    child_platform_data_maps: [],
                    is_optional: true,
                },
                {
                    id: '5f31490d66dba60c29f65dc3',
                    key: 'geo_data',
                    var_type: VarType.OBJECT,
                    input_type: InputType.OBJECT_INPUT,
                    default_value: null,
                    option_values: null,
                    __typename: 'PlatformDataMap',
                    description: '...',
                    is_optional: true,
                    child_platform_data_maps: [
                        {
                            id: '5f31490d66dba60c29f65db2',
                            key: 'test_types',
                            var_type: VarType.OBJECT,
                            input_type: InputType.OBJECT_INPUT,
                            default_value: null,
                            option_values: null,
                            __typename: 'PlatformDataMap',
                            description: '...',
                            child_platform_data_maps: [
                                {
                                    id: '5f31490d66dba60c29f65da1',
                                    key: 'test_number',
                                    var_type: VarType.INT,
                                    input_type: InputType.INT_INPUT,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490d66dba60c29f65da2',
                                    key: 'test_hidden',
                                    var_type: VarType.STRING,
                                    input_type: InputType.TEXT,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490d66dba60c29f65da3',
                                    key: 'test_text',
                                    var_type: VarType.ARRAY_STRING,
                                    input_type: InputType.TEXT,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490d66dba60c29f65da4',
                                    key: 'test_checkbox',
                                    var_type: VarType.BOOLEAN,
                                    input_type: InputType.CHECKBOX,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490d66dba60c29f65da5',
                                    key: 'test_date',
                                    var_type: VarType.STRING,
                                    input_type: InputType.DATE_STRING,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490d66dba60c29f65da6',
                                    key: 'test_date_tim',
                                    var_type: VarType.STRING,
                                    input_type: InputType.DATETIME_STRING,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490d66dba60c29f65da7',
                                    key: 'test_textarea',
                                    var_type: VarType.STRING,
                                    input_type: InputType.TEXTAREA,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                                {
                                    id: '5f31490dxxc9f65da7',
                                    key: 'test_country',
                                    var_type: VarType.STRING,
                                    input_type: InputType.COUNTRY_CODE_SELECT,
                                    default_value: null,
                                    option_values: null,
                                    __typename: 'PlatformDataMap',
                                    description: '...',
                                    is_optional: true,
                                    child_platform_data_maps: [],
                                },
                            ],
                            is_optional: true,
                        },
                        {
                            id: '5f31490d66dba60c29f65db2',
                            key: 'country_code',
                            var_type: VarType.STRING,
                            input_type: InputType.TEXT,
                            default_value: null,
                            option_values: null,
                            __typename: 'PlatformDataMap',
                            description: '...',
                            child_platform_data_maps: [],
                            is_optional: true,
                        },
                        {
                            id: '5f31490d66dba60c29f65db3',
                            key: 'subdivision_codes',
                            var_type: VarType.ARRAY_STRING,
                            input_type: InputType.TEXT,
                            default_value: null,
                            option_values: null,
                            __typename: 'PlatformDataMap',
                            description: '...',
                            child_platform_data_maps: [],
                            is_optional: true,
                        },
                    ],
                },
                {
                    id: '5f31490d66dba60c29f65dc4',
                    key: 'platform_vars',
                    var_type: VarType.ARRAY_OBJECT,
                    input_type: InputType.OBJECT_ARRAY_INPUT,
                    default_value: null,
                    option_values: null,
                    __typename: 'PlatformDataMap',
                    description: '...',
                    is_optional: true,
                    child_platform_data_maps: [
                        {
                            id: '5f31490d66dba60c29f65db4',
                            key: 'key',
                            var_type: VarType.STRING,
                            input_type: InputType.TEXT,
                            default_value: null,
                            option_values: null,
                            __typename: 'PlatformDataMap',
                            description: '...',
                            child_platform_data_maps: [],
                            is_optional: true,
                        },
                        {
                            id: '5f31490d66dba60c29f65db5',
                            key: 'value',
                            var_type: VarType.ARRAY_STRING,
                            input_type: InputType.TEXT,
                            default_value: null,
                            option_values: null,
                            __typename: 'PlatformDataMap',
                            description: '...',
                            child_platform_data_maps: [],
                            is_optional: true,
                        },
                        {
                            id: '5f31490cxxxba60c29f65db5',
                            key: 'rawObj',
                            var_type: VarType.OBJECT,
                            input_type: InputType.OBJECT_INPUT,
                            default_value: null,
                            option_values: null,
                            __typename: 'PlatformDataMap',
                            description: '...',
                            child_platform_data_maps: [],
                            is_optional: true,
                        },
                    ],
                },
            ],
            __typename: 'PlatformDataContainer',
            description: '...',
        },
    ] as DataContainer[],
};

export { mockDataContainers };
