export enum DataManagerStringMacros {
    S8_DATE_TIME_UTC = '%S8_DATE_TIME_UTC%',
    S8_USER_HASH = '%S8_USER_HASH%',
    S8_USER_IP = '%S8_USER_IP%',
    S8_USER_AGENT = '%S8_USER_AGENT%',
    S8_USER_COUNTRY_CODE = '%S8_USER_COUNTRY_CODE%',
    S8_ORG_ID = '%S8_ORG_ID%',
    S8_INGEST_ENDPOINT_ID = '%S8_INGEST_ENDPOINT_ID%',
    S8_INGEST_ENV_ID = '%S8_INGEST_ENV_ID%',
    S8_INGEST_REVISION_ID = '%S8_INGEST_REVISION_ID%',
    S8_BROWSER_NAME = '%S8_BROWSER_NAME%',
    S8_BROWSER_VERSION = '%S8_BROWSER_VERSION%',
    S8_BROWSER_MINOR_VERSION = '%S8_BROWSER_MINOR_VERSION%',
    S8_OS_NAME = '%S8_OS_NAME%',
    S8_OS_VERSION = '%S8_OS_VERSION%',
    S8_OS_MINOR_VERSION = '%S8_OS_MINOR_VERSION%',
    S8_OS_PATCH_VERSION = '%S8_OS_PATCH_VERSION%',
    S8_DEVICE_NAME = '%S8_DEVICE_NAME%',
    S8_DEVICE_MODEL = '%S8_DEVICE_MODEL%',
    S8_DEVICE_BRAND = '%S8_DEVICE_BRAND%',
}

export enum DataManagerIntegerMacros {
    S8_RANDOM_INTEGER = '%S8_RANDOM_INTEGER%',
    S8_TIME_STAMP_UTC = '%S8_TIME_STAMP_UTC%',
}

export enum DataManagerFloatMacros {}

export enum DataManagerBooleanMacros {}

export enum DataManagerDateTimeMacros {
    S8_DATE_TIME_UTC = '%S8_DATE_TIME_UTC%',
}

export enum DataManagerTimestampMacros {
    S8_TIME_STAMP_UTC = '%S8_TIME_STAMP_UTC%',
}
